version: "3.9"
services:
    web:
        build: 
                context: ./PaymentGateway/PaymentGateway
                dockerfile: PaymentGateway.Api/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Pa55w0rd"
            ACCEPT_EULA: "Y"
    app:
        build:
            context: ./FakeBankService
            dockerfile: Dockerfile
        ports:
            - "8080:8080"